gitignore: don't ignore .i files
* 10or has some .i files which are being included, in drivers/input/touchscreen/focaltech_touch/include/firmware/

fixes the missing file compilatipon error

../drivers/input/touchscreen/focaltech_touch/focaltech_flash.c:52:28: fatal error: include/firmware/LQ_L8600_FT6336U_app.i: No such file or directory
 #include FTS_UPGRADE_FW_APP
                            ^
compilation terminated.

Signed-off-by: innfinite4evr <innfinite4evr@gmail.com>